### ISSUE TITLE
Projects deadline

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2020_01_Jenkins#1]
Please keep in mind that the projects need to be presented before the end of exam period (1st October). In order to achieve that, we urge the teams to submit their projects as soon as possible so that we can have a proper review/revision period which usually lasts one week. Please note that if projects are submitted sooner, more dates will be available for presentations, because as exam period nears its end, our duties increase and our time slots are severely narrowed.

With all that being said, the optimal deadline for project submissions is **17th September**.

Thank you for understanding.

**Comment by Laleee** [comment]
Done.
